"""hacer cod_actividad y desc_actividad opcionales en clientes

Revision ID: 08864e58a7af
Revises: 94482431feae
Create Date: 2026-07-16 15:09:28.310398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08864e58a7af'
down_revision: Union[str, Sequence[str], None] = '94482431feae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clientes', 'cod_actividad',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('clientes', 'desc_actividad',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clientes', 'desc_actividad',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('clientes', 'cod_actividad',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
