"""hacer campos de ingresos obligatorios

Revision ID: 088dd20f5b24
Revises: 685e1a46f349
Create Date: 2026-07-09 13:34:51.797689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '088dd20f5b24'
down_revision: Union[str, Sequence[str], None] = '685e1a46f349'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingresos', 'dte',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('ingresos', 'sello',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('ingresos', 'codigo_generacion',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('ingresos', 'cotizacion',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('ingresos', 'observaciones',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingresos', 'observaciones',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('ingresos', 'cotizacion',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('ingresos', 'codigo_generacion',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('ingresos', 'sello',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('ingresos', 'dte',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
