"""correcion del modelo emisor correo adicional

Revision ID: 18c6d1af1f1e
Revises: faa73a8e05dc
Create Date: 2026-07-21 16:57:05.619217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18c6d1af1f1e'
down_revision: Union[str, Sequence[str], None] = 'faa73a8e05dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emisor', sa.Column('correo_interno', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emisor', 'correo_interno')
    # ### end Alembic commands ###
