"""crear modelos de usuarios

Revision ID: 2190e9a3e100
Revises: 9a89d4e893e8
Create Date: 2026-07-08 14:18:16.889362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2190e9a3e100'
down_revision: Union[str, Sequence[str], None] = '9a89d4e893e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingresos', sa.Column('codigo_generacion', sa.String(length=100), nullable=True))
    op.drop_index(op.f('ix_ingresos_codigo_origen'), table_name='ingresos')
    op.create_index(op.f('ix_ingresos_codigo_generacion'), 'ingresos', ['codigo_generacion'], unique=False)
    op.drop_column('ingresos', 'codigo_origen')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingresos', sa.Column('codigo_origen', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_ingresos_codigo_generacion'), table_name='ingresos')
    op.create_index(op.f('ix_ingresos_codigo_origen'), 'ingresos', ['codigo_origen'], unique=False)
    op.drop_column('ingresos', 'codigo_generacion')
    # ### end Alembic commands ###
