"""Creacion de modelos de emisor

Revision ID: 274a11b82c47
Revises: 08864e58a7af
Create Date: 2026-07-21 13:58:05.091383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '274a11b82c47'
down_revision: Union[str, Sequence[str], None] = '08864e58a7af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emisor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nit', sa.String(length=17), nullable=False),
    sa.Column('nrc', sa.String(length=8), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('nombre_comercial', sa.String(length=150), nullable=False),
    sa.Column('cod_actividad', sa.String(length=6), nullable=False),
    sa.Column('desc_actividad', sa.String(length=150), nullable=False),
    sa.Column('dir_departamento', sa.String(length=50), nullable=False),
    sa.Column('dir_municipio', sa.String(length=50), nullable=False),
    sa.Column('dir_distrito', sa.String(length=50), nullable=False),
    sa.Column('dir_complemento', sa.String(length=200), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('cod_estable', sa.String(length=4), nullable=False),
    sa.Column('cod_punto_venta', sa.String(length=15), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emisor_activo'), 'emisor', ['activo'], unique=False)
    op.create_index(op.f('ix_emisor_id'), 'emisor', ['id'], unique=False)
    op.create_index(op.f('ix_emisor_nit'), 'emisor', ['nit'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emisor_nit'), table_name='emisor')
    op.drop_index(op.f('ix_emisor_id'), table_name='emisor')
    op.drop_index(op.f('ix_emisor_activo'), table_name='emisor')
    op.drop_table('emisor')
    # ### end Alembic commands ###
