"""Correccion de modulo producto corregido

Revision ID: 2c49f60438aa
Revises: a295523ccce0
Create Date: 2026-07-24 16:32:29.855952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c49f60438aa'
down_revision: Union[str, Sequence[str], None] = 'a295523ccce0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_productos_bodega_id'), table_name='productos')
    op.drop_constraint(op.f('productos_bodega_id_fkey'), 'productos', type_='foreignkey')
    op.drop_column('productos', 'bodega_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('bodega_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('productos_bodega_id_fkey'), 'productos', 'bodegas', ['bodega_id'], ['id'])
    op.create_index(op.f('ix_productos_bodega_id'), 'productos', ['bodega_id'], unique=False)
    # ### end Alembic commands ###
