"""hacer campos de items obligatorios

Revision ID: 685e1a46f349
Revises: e78da7d4c3f4
Create Date: 2026-07-09 13:10:18.483236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '685e1a46f349'
down_revision: Union[str, Sequence[str], None] = 'e78da7d4c3f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'estado_item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('items', 'serie',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('items', 'dias_stock',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'dias_stock',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('items', 'serie',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('items', 'estado_item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
