"""agregar movimientos y tipos_movimiento

Revision ID: 6a98b20d6eab
Revises: 2c49f60438aa
Create Date: 2026-09-14 16:01:19.289496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a98b20d6eab'
down_revision: Union[str, Sequence[str], None] = '2c49f60438aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipos_movimiento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('observaciones', sa.String(length=150), nullable=True),
    sa.Column('afecta_suma', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipos_movimiento_activo'), 'tipos_movimiento', ['activo'], unique=False)
    op.create_index(op.f('ix_tipos_movimiento_id'), 'tipos_movimiento', ['id'], unique=False)
    op.create_index(op.f('ix_tipos_movimiento_nombre'), 'tipos_movimiento', ['nombre'], unique=True)
    op.create_table('movimientos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('tipo_movimiento_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('bodega_origen_id', sa.Integer(), nullable=True),
    sa.Column('bodega_destino_id', sa.Integer(), nullable=True),
    sa.Column('saldo_anterior', sa.Integer(), nullable=False),
    sa.Column('saldo_nuevo', sa.Integer(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bodega_destino_id'], ['bodegas.id'], ),
    sa.ForeignKeyConstraint(['bodega_origen_id'], ['bodegas.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['tipo_movimiento_id'], ['tipos_movimiento.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimientos_bodega_destino_id'), 'movimientos', ['bodega_destino_id'], unique=False)
    op.create_index(op.f('ix_movimientos_bodega_origen_id'), 'movimientos', ['bodega_origen_id'], unique=False)
    op.create_index(op.f('ix_movimientos_fecha'), 'movimientos', ['fecha'], unique=False)
    op.create_index(op.f('ix_movimientos_id'), 'movimientos', ['id'], unique=False)
    op.create_index(op.f('ix_movimientos_item_id'), 'movimientos', ['item_id'], unique=False)
    op.create_index(op.f('ix_movimientos_tipo_movimiento_id'), 'movimientos', ['tipo_movimiento_id'], unique=False)
    op.create_index(op.f('ix_movimientos_usuario_id'), 'movimientos', ['usuario_id'], unique=False)
    op.add_column('items', sa.Column('cantidad_inicial', sa.Integer(), nullable=False))
    op.add_column('items', sa.Column('cantidad_actual', sa.Integer(), nullable=False))
    op.add_column('productos', sa.Column('vendible_granel', sa.Boolean(), nullable=False))
    op.add_column('productos', sa.Column('qty_contenido', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productos', 'qty_contenido')
    op.drop_column('productos', 'vendible_granel')
    op.drop_column('items', 'cantidad_actual')
    op.drop_column('items', 'cantidad_inicial')
    op.drop_index(op.f('ix_movimientos_usuario_id'), table_name='movimientos')
    op.drop_index(op.f('ix_movimientos_tipo_movimiento_id'), table_name='movimientos')
    op.drop_index(op.f('ix_movimientos_item_id'), table_name='movimientos')
    op.drop_index(op.f('ix_movimientos_id'), table_name='movimientos')
    op.drop_index(op.f('ix_movimientos_fecha'), table_name='movimientos')
    op.drop_index(op.f('ix_movimientos_bodega_origen_id'), table_name='movimientos')
    op.drop_index(op.f('ix_movimientos_bodega_destino_id'), table_name='movimientos')
    op.drop_table('movimientos')
    op.drop_index(op.f('ix_tipos_movimiento_nombre'), table_name='tipos_movimiento')
    op.drop_index(op.f('ix_tipos_movimiento_id'), table_name='tipos_movimiento')
    op.drop_index(op.f('ix_tipos_movimiento_activo'), table_name='tipos_movimiento')
    op.drop_table('tipos_movimiento')
    # ### end Alembic commands ###
