"""crear tablas de productos

Revision ID: 867badc32e0b
Revises: b13a88e73bbf
Create Date: 2026-07-03 13:38:46.479368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '867badc32e0b'
down_revision: Union[str, Sequence[str], None] = 'b13a88e73bbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorias_id'), 'categorias', ['id'], unique=False)
    op.create_index(op.f('ix_categorias_nombre'), 'categorias', ['nombre'], unique=True)
    op.create_table('bodegas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('ubicacion', sa.String(length=150), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('encargado_id', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['encargado_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bodegas_activo'), 'bodegas', ['activo'], unique=False)
    op.create_index(op.f('ix_bodegas_encargado_id'), 'bodegas', ['encargado_id'], unique=False)
    op.create_index(op.f('ix_bodegas_id'), 'bodegas', ['id'], unique=False)
    op.create_index(op.f('ix_bodegas_nombre'), 'bodegas', ['nombre'], unique=True)
    op.create_table('productos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('tipo', sa.Enum('BIEN', 'SERVICIO', name='tipoproducto'), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('bodega_id', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bodega_id'], ['bodegas.id'], ),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productos_activo'), 'productos', ['activo'], unique=False)
    op.create_index(op.f('ix_productos_bodega_id'), 'productos', ['bodega_id'], unique=False)
    op.create_index(op.f('ix_productos_categoria_id'), 'productos', ['categoria_id'], unique=False)
    op.create_index(op.f('ix_productos_id'), 'productos', ['id'], unique=False)
    op.create_index(op.f('ix_productos_nombre'), 'productos', ['nombre'], unique=False)
    op.create_index(op.f('ix_productos_tipo'), 'productos', ['tipo'], unique=False)
    op.create_table('precios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('precio_base', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('precio_costo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('precio_publico', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('precio_iva', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('precio_promo', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('precio_descuento', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_precios_activo'), 'precios', ['activo'], unique=False)
    op.create_index(op.f('ix_precios_id'), 'precios', ['id'], unique=False)
    op.create_index(op.f('ix_precios_producto_id'), 'precios', ['producto_id'], unique=True)
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('bodega_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('cantidad_minima', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bodega_id'], ['bodegas.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stocks_activo'), 'stocks', ['activo'], unique=False)
    op.create_index(op.f('ix_stocks_bodega_id'), 'stocks', ['bodega_id'], unique=False)
    op.create_index(op.f('ix_stocks_id'), 'stocks', ['id'], unique=False)
    op.create_index(op.f('ix_stocks_producto_id'), 'stocks', ['producto_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stocks_producto_id'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_id'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_bodega_id'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_activo'), table_name='stocks')
    op.drop_table('stocks')
    op.drop_index(op.f('ix_precios_producto_id'), table_name='precios')
    op.drop_index(op.f('ix_precios_id'), table_name='precios')
    op.drop_index(op.f('ix_precios_activo'), table_name='precios')
    op.drop_table('precios')
    op.drop_index(op.f('ix_productos_tipo'), table_name='productos')
    op.drop_index(op.f('ix_productos_nombre'), table_name='productos')
    op.drop_index(op.f('ix_productos_id'), table_name='productos')
    op.drop_index(op.f('ix_productos_categoria_id'), table_name='productos')
    op.drop_index(op.f('ix_productos_bodega_id'), table_name='productos')
    op.drop_index(op.f('ix_productos_activo'), table_name='productos')
    op.drop_table('productos')
    op.drop_index(op.f('ix_bodegas_nombre'), table_name='bodegas')
    op.drop_index(op.f('ix_bodegas_id'), table_name='bodegas')
    op.drop_index(op.f('ix_bodegas_encargado_id'), table_name='bodegas')
    op.drop_index(op.f('ix_bodegas_activo'), table_name='bodegas')
    op.drop_table('bodegas')
    op.drop_index(op.f('ix_categorias_nombre'), table_name='categorias')
    op.drop_index(op.f('ix_categorias_id'), table_name='categorias')
    op.drop_table('categorias')
    # ### end Alembic commands ###
