"""crear tabla clientes

Revision ID: 94482431feae
Revises: d9541da3887f
Create Date: 2026-07-16 11:50:38.033061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94482431feae'
down_revision: Union[str, Sequence[str], None] = 'd9541da3887f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_comercial', sa.String(length=150), nullable=True),
    sa.Column('nombre', sa.String(length=150), nullable=True),
    sa.Column('dui', sa.String(length=20), nullable=True),
    sa.Column('nit', sa.String(length=30), nullable=True),
    sa.Column('nrc', sa.String(length=20), nullable=True),
    sa.Column('pasaporte', sa.String(length=50), nullable=True),
    sa.Column('cod_actividad', sa.String(length=50), nullable=False),
    sa.Column('desc_actividad', sa.String(length=255), nullable=False),
    sa.Column('cod_departamento', sa.String(length=50), nullable=False),
    sa.Column('desc_departamento', sa.String(length=100), nullable=False),
    sa.Column('cod_municipio', sa.String(length=50), nullable=False),
    sa.Column('desc_municipio', sa.String(length=100), nullable=False),
    sa.Column('cod_distrito', sa.String(length=50), nullable=False),
    sa.Column('desc_distrito', sa.String(length=100), nullable=False),
    sa.Column('cod_tipopersona', sa.String(length=50), nullable=False),
    sa.Column('desc_tipopersona', sa.String(length=100), nullable=False),
    sa.Column('percep_iva', sa.Boolean(), nullable=False),
    sa.Column('iva', sa.Boolean(), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('correo', sa.String(length=150), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_activo'), 'clientes', ['activo'], unique=False)
    op.create_index(op.f('ix_clientes_correo'), 'clientes', ['correo'], unique=True)
    op.create_index(op.f('ix_clientes_dui'), 'clientes', ['dui'], unique=False)
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_index(op.f('ix_clientes_nit'), 'clientes', ['nit'], unique=False)
    op.create_index(op.f('ix_clientes_nrc'), 'clientes', ['nrc'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clientes_nrc'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_nit'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_dui'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_correo'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_activo'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
