"""crear tabla estado ingreso y borrado de columna descripcion y activo en estado items

Revision ID: 9a89d4e893e8
Revises: cbfac1fc5754
Create Date: 2026-07-07 15:19:45.006011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a89d4e893e8'
down_revision: Union[str, Sequence[str], None] = 'cbfac1fc5754'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estado_ingreso',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_estado', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estado_ingreso_id'), 'estado_ingreso', ['id'], unique=False)
    op.create_index(op.f('ix_estado_ingreso_nombre_estado'), 'estado_ingreso', ['nombre_estado'], unique=False)
    op.drop_index(op.f('ix_estado_items_activo'), table_name='estado_items')
    op.drop_column('estado_items', 'activo')
    op.drop_column('estado_items', 'descripcion')
    op.add_column('ingresos', sa.Column('estado_ingreso_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_ingresos_estado_ingreso_id'), 'ingresos', ['estado_ingreso_id'], unique=False)
    op.create_foreign_key(None, 'ingresos', 'estado_ingreso', ['estado_ingreso_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ingresos', type_='foreignkey')
    op.drop_index(op.f('ix_ingresos_estado_ingreso_id'), table_name='ingresos')
    op.drop_column('ingresos', 'estado_ingreso_id')
    op.add_column('estado_items', sa.Column('descripcion', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('estado_items', sa.Column('activo', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_estado_items_activo'), 'estado_items', ['activo'], unique=False)
    op.drop_index(op.f('ix_estado_ingreso_nombre_estado'), table_name='estado_ingreso')
    op.drop_index(op.f('ix_estado_ingreso_id'), table_name='estado_ingreso')
    op.drop_table('estado_ingreso')
    # ### end Alembic commands ###
