"""Crear modelo de permisos y tabla intermedaria

Revision ID: a295523ccce0
Revises: 18c6d1af1f1e
Create Date: 2026-07-23 11:18:59.817940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a295523ccce0'
down_revision: Union[str, Sequence[str], None] = '18c6d1af1f1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permisos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('modulo', sa.String(length=50), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permisos_activo'), 'permisos', ['activo'], unique=False)
    op.create_index(op.f('ix_permisos_codigo'), 'permisos', ['codigo'], unique=True)
    op.create_index(op.f('ix_permisos_id'), 'permisos', ['id'], unique=False)
    op.create_index(op.f('ix_permisos_modulo'), 'permisos', ['modulo'], unique=False)
    op.create_table('rol_permisos',
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('permiso_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['permiso_id'], ['permisos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rol_id', 'permiso_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rol_permisos')
    op.drop_index(op.f('ix_permisos_modulo'), table_name='permisos')
    op.drop_index(op.f('ix_permisos_id'), table_name='permisos')
    op.drop_index(op.f('ix_permisos_codigo'), table_name='permisos')
    op.drop_index(op.f('ix_permisos_activo'), table_name='permisos')
    op.drop_table('permisos')
    # ### end Alembic commands ###
