"""crear tablas proveedores e inventario

Revision ID: cbfac1fc5754
Revises: 21126a78e351
Create Date: 2026-07-06 16:55:33.433483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbfac1fc5754'
down_revision: Union[str, Sequence[str], None] = '21126a78e351'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estado_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estado_items_activo'), 'estado_items', ['activo'], unique=False)
    op.create_index(op.f('ix_estado_items_estado'), 'estado_items', ['estado'], unique=True)
    op.create_index(op.f('ix_estado_items_id'), 'estado_items', ['id'], unique=False)
    op.create_table('proveedores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('contacto', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('telefono1', sa.String(length=20), nullable=True),
    sa.Column('telefono2', sa.String(length=20), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proveedores_activo'), 'proveedores', ['activo'], unique=False)
    op.create_index(op.f('ix_proveedores_email'), 'proveedores', ['email'], unique=False)
    op.create_index(op.f('ix_proveedores_id'), 'proveedores', ['id'], unique=False)
    op.create_index(op.f('ix_proveedores_nombre'), 'proveedores', ['nombre'], unique=False)
    op.create_table('ingresos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('dte', sa.String(length=50), nullable=True),
    sa.Column('sello', sa.String(length=100), nullable=True),
    sa.Column('codigo_origen', sa.String(length=100), nullable=True),
    sa.Column('cotizacion', sa.String(length=50), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingresos_activo'), 'ingresos', ['activo'], unique=False)
    op.create_index(op.f('ix_ingresos_codigo_origen'), 'ingresos', ['codigo_origen'], unique=False)
    op.create_index(op.f('ix_ingresos_dte'), 'ingresos', ['dte'], unique=False)
    op.create_index(op.f('ix_ingresos_fecha'), 'ingresos', ['fecha'], unique=False)
    op.create_index(op.f('ix_ingresos_id'), 'ingresos', ['id'], unique=False)
    op.create_index(op.f('ix_ingresos_proveedor_id'), 'ingresos', ['proveedor_id'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ingreso_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('bodega_id', sa.Integer(), nullable=False),
    sa.Column('estado_item_id', sa.Integer(), nullable=True),
    sa.Column('serie', sa.String(length=100), nullable=True),
    sa.Column('dte', sa.String(length=50), nullable=True),
    sa.Column('dias_stock', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bodega_id'], ['bodegas.id'], ),
    sa.ForeignKeyConstraint(['estado_item_id'], ['estado_items.id'], ),
    sa.ForeignKeyConstraint(['ingreso_id'], ['ingresos.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_activo'), 'items', ['activo'], unique=False)
    op.create_index(op.f('ix_items_bodega_id'), 'items', ['bodega_id'], unique=False)
    op.create_index(op.f('ix_items_estado_item_id'), 'items', ['estado_item_id'], unique=False)
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_index(op.f('ix_items_ingreso_id'), 'items', ['ingreso_id'], unique=False)
    op.create_index(op.f('ix_items_producto_id'), 'items', ['producto_id'], unique=False)
    op.create_index(op.f('ix_items_serie'), 'items', ['serie'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_serie'), table_name='items')
    op.drop_index(op.f('ix_items_producto_id'), table_name='items')
    op.drop_index(op.f('ix_items_ingreso_id'), table_name='items')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_index(op.f('ix_items_estado_item_id'), table_name='items')
    op.drop_index(op.f('ix_items_bodega_id'), table_name='items')
    op.drop_index(op.f('ix_items_activo'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_ingresos_proveedor_id'), table_name='ingresos')
    op.drop_index(op.f('ix_ingresos_id'), table_name='ingresos')
    op.drop_index(op.f('ix_ingresos_fecha'), table_name='ingresos')
    op.drop_index(op.f('ix_ingresos_dte'), table_name='ingresos')
    op.drop_index(op.f('ix_ingresos_codigo_origen'), table_name='ingresos')
    op.drop_index(op.f('ix_ingresos_activo'), table_name='ingresos')
    op.drop_table('ingresos')
    op.drop_index(op.f('ix_proveedores_nombre'), table_name='proveedores')
    op.drop_index(op.f('ix_proveedores_id'), table_name='proveedores')
    op.drop_index(op.f('ix_proveedores_email'), table_name='proveedores')
    op.drop_index(op.f('ix_proveedores_activo'), table_name='proveedores')
    op.drop_table('proveedores')
    op.drop_index(op.f('ix_estado_items_id'), table_name='estado_items')
    op.drop_index(op.f('ix_estado_items_estado'), table_name='estado_items')
    op.drop_index(op.f('ix_estado_items_activo'), table_name='estado_items')
    op.drop_table('estado_items')
    # ### end Alembic commands ###
