"""agregar usuario_id a ingresos

Revision ID: d9541da3887f
Revises: 088dd20f5b24
Create Date: 2026-07-09 16:25:09.152183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9541da3887f'
down_revision: Union[str, Sequence[str], None] = '088dd20f5b24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingresos', sa.Column('usuario_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_ingresos_usuario_id'), 'ingresos', ['usuario_id'], unique=False)
    op.create_foreign_key(None, 'ingresos', 'usuarios', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ingresos', type_='foreignkey')
    op.drop_index(op.f('ix_ingresos_usuario_id'), table_name='ingresos')
    op.drop_column('ingresos', 'usuario_id')
    # ### end Alembic commands ###
