"""Agregar campo observaciones a la tabla estado_items

Revision ID: e78da7d4c3f4
Revises: 2707f7fb50e1
Create Date: 2026-07-08 15:17:22.077025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e78da7d4c3f4'
down_revision: Union[str, Sequence[str], None] = '2707f7fb50e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estado_items', sa.Column('observaciones', sa.String(length=100), nullable=False))
    op.create_index(op.f('ix_estado_items_observaciones'), 'estado_items', ['observaciones'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_estado_items_observaciones'), table_name='estado_items')
    op.drop_column('estado_items', 'observaciones')
    # ### end Alembic commands ###
