"""correcion del modelo emisor

Revision ID: faa73a8e05dc
Revises: 274a11b82c47
Create Date: 2026-07-21 16:33:57.316433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faa73a8e05dc'
down_revision: Union[str, Sequence[str], None] = '274a11b82c47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emisor', sa.Column('cod_departamento', sa.String(length=50), nullable=False))
    op.add_column('emisor', sa.Column('desc_departamento', sa.String(length=50), nullable=False))
    op.add_column('emisor', sa.Column('cod_municipio', sa.String(length=50), nullable=False))
    op.add_column('emisor', sa.Column('desc_municipio', sa.String(length=50), nullable=False))
    op.add_column('emisor', sa.Column('cod_distrito', sa.String(length=50), nullable=False))
    op.add_column('emisor', sa.Column('desc_distrito', sa.String(length=50), nullable=False))
    op.add_column('emisor', sa.Column('dirr_complemento', sa.String(length=200), nullable=False))
    op.drop_column('emisor', 'dir_distrito')
    op.drop_column('emisor', 'dir_departamento')
    op.drop_column('emisor', 'dir_municipio')
    op.drop_column('emisor', 'dir_complemento')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emisor', sa.Column('dir_complemento', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('emisor', sa.Column('dir_municipio', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('emisor', sa.Column('dir_departamento', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('emisor', sa.Column('dir_distrito', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('emisor', 'dirr_complemento')
    op.drop_column('emisor', 'desc_distrito')
    op.drop_column('emisor', 'cod_distrito')
    op.drop_column('emisor', 'desc_municipio')
    op.drop_column('emisor', 'cod_municipio')
    op.drop_column('emisor', 'desc_departamento')
    op.drop_column('emisor', 'cod_departamento')
    # ### end Alembic commands ###
